### ISSUE TITLE
Return whether sensor data is from cache or not

### ISSUE THREAD

**Issue by ravage84** [orca-services/cakephp-heartbeat#7]
We regularly update our servers (automatically & manually), as we should.

Before we update a server, we normally open the heartbeat to manually check whether everything is OK with the software.
After we updated a server, we come back to manually check the heartbeat. Depending on the cache time, some if not most sensor results are cached. 

Curently there is no clear way to see whether those results  are cached or not, except for comparing the ``lastExecuted`` time with the current time when returning it as JSON.

It would be preferable to see it clearly whether each result was from cache or not, like a boolean ``cached``. In the HTML UI this could be displayed in some nice way, too.

**Comment by ravage84** [comment]
@liviascapin might be worthwile to implement this, as we currently work on the plugin...

**Comment by mentisy** [comment]
@ravage84 I guess this can be closed now.
